name: Vercel Production Deployment

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
  NEON_DATABASE_URL_UNPOOLED: ${{ secrets.NEON_PROD_DATABASE_URL_UNPOOLED }}
  NEON_DATABASE_URL: ${{ secrets.NEON_PROD_DATABASE_URL }}

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  unit:
    name: Unit Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.1.2
          run_install: |
            - recursive: true
              args: [--frozen-lockfile]

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.13.1
          cache: "pnpm"

      - name: Test Units In Code
        run: npm run test:unit

  integration:
    name: Integration Testing
    runs-on: ubuntu-latest
    needs: unit
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.1.2
          run_install: |
            - recursive: true
              args: [--frozen-lockfile]

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.13.1
          cache: "pnpm"

      - name: Test Modules Containing Units
        run: npm run test:integration

  e2e:
    name: End to End Testing
    runs-on: ubuntu-latest
    needs: integration
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.1.2
          run_install: |
            - recursive: true
              args: [--frozen-lockfile]

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.13.1
          cache: "pnpm"

      - name: Test End to End Application
        run: npm run test:e2e

  deploy:
    name: Deploy Web App
    runs-on: ubuntu-latest
    needs: e2e
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.1.2
          run_install: |
            - recursive: true
              args: [--frozen-lockfile]

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.13.1
          cache: "pnpm"

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --prod --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt --prod --token=${{ secrets.VERCEL_TOKEN }}
